### ISSUE TITLE
Fix problems with CSS for MovieDetails page

### ISSUE THREAD

**Issue by SGierszewski** [lmachens/photoplay#65]
**What?**
1) picture position on page is not correct, it sees there are unnecessary margins set to the image
2) title and genre should be displayed as a layer on top of the picture
3) "Watch now" button is too wide
4) Scroll function is not correctly implemented. Cast cannot be displayed properly.

**Reproduce**
We used "small mobile" view to display the MovieDetails page.

**Possible solutions**
1) Delete picture margins
2) Maybe include a z-index 
3) Change button width
4) Check scroll function in CSS, maybe not set for the whole container?

**Comment by roabram** [comment]
WEB-BR-5

**Comment by roabram** [comment]
fixed problems 1-3
